version: '1'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'notes'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: notesdb
    volumes:
      - postgres-data:/var/lib/postgresql/data



volumes:
  postgres-data: