CREATE TABLE IF NOT EXISTS note
(
id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(55) NOT NULL,
text TEXT NOT NULL,
create_date TIMESTAMP NOT NULL
);

INSERT INTO note (name, text, create_date) VALUES
('первая заметка', 'Тестовая самая крутая заметка', '2023-10-13 21:27:00');